version: '3.3'
services:

  # Infrastructure
  # ============================================================================
  # Config server
  config-server:
    image: raw/spring-petclinic-config-server
    container_name: raw-config-server
    entrypoint: ["sh", "-c","
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8888:8888

  # Discovery service
  discovery-server:
    image: raw/spring-petclinic-discovery-server
    container_name: raw-discovery-server
    depends_on:
      - config-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8761:8761

  # Hystrix dashboard
  hystrix-dashboard:
    image: raw/spring-petclinic-hystrix-dashboard
    container_name: raw-hystrix-dashboard
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
     - 7979:7979

  # Admin server
  admin-server:
    image: raw/spring-petclinic-admin-server
    container_name: raw-admin-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
     - 9090:9090

  # Services
  # ============================================================================
  # Customers service
  customers-service:
    image: raw/spring-petclinic-customers-service
    container_name: raw-customers-service
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8081:8081

  # Visits service
  visits-service:
    image: raw/spring-petclinic-visits-service
    container_name: raw-visits-service
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8082:8082

  #Vets service
  vets-service:
    image: raw/spring-petclinic-vets-service
    container_name: raw-vets-service
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8083:8083

  # API gateway
  api-gateway:
    image: raw/spring-petclinic-api-gateway
    container_name: raw-api-gateway
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=120s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8080:8080

  # Load
  # ============================================================================
  # Load server
  load-server:
    build: ./docker/load-server
    image: raw/load-server
    container_name: raw-load-server
    depends_on:
      - api-gateway
      - customers-service
      - visits-service
      - vets-service
    links:
      - api-gateway
      - customers-service
      - visits-service
      - vets-service
